"""
Django settings for savannah project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-itqo=#@@gki)d34oq-oev3n=lhw$xfxo3&7vg^e)xciwq=&&-o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
    'debug_toolbar',
    'rest_framework',
    'mozilla_django_oidc',
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'mozilla_django_oidc.middleware.SessionRefresh',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'savannah.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'savannah.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'savannah_db',
        'USER': 'postgres',
        'PASSWORD': 'pass',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "localhost"
EMAIL_PORT = 2525
EMAIL_HOST_USER = " "
EMAIL_HOST_PASSWORD = " "
DEFAULT_FROM_EMAIL = "jafethadet@gmail.com"
ADMIN_EMAIL = "admin@myshop.com"

# OpenID Connect settings
AUTHENTICATION_BACKENDS = (
    'mozilla_django_oidc.auth.OIDCAuthenticationBackend',
    'django.contrib.auth.backends.ModelBackend',
)

LOGIN_URL = 'oidc_authentication_init'
LOGIN_REDIRECT_URL = '/shop/customer/'
LOGOUT_REDIRECT_URL = '/'

# Auth0 specific settings
OIDC_RP_CLIENT_ID = 'RU0EzbYMg2GgxIE0kPR7AVuA9dNg4tix'
OIDC_RP_CLIENT_SECRET = '2u9z1ClZUdbNFdbDZxvZQXr47YqjBrwgVc1yu0W9qv1a72JEX08072xZr29GVpCA'
OIDC_OP_AUTHORIZATION_ENDPOINT = 'https://savannah-shop.us.auth0.com/authorize'
OIDC_OP_TOKEN_ENDPOINT = 'https://savannah-shop.us.auth0.com/oauth/token'
OIDC_OP_USER_ENDPOINT = 'https://savannah-shop.us.auth0.com/userinfo'

# Optional settings
OIDC_VERIFY_SSL = True
OIDC_USERNAME_ALGO = 'shop.oidc.generate_username'
OIDC_CREATE_USER = True


AFRICASTALKING_USERNAME = "savannah-shop"
AFRICASTALKING_API_KEY = "atsk_2329d7a7fea678d0cbec3ac6236cc56dd6b3d7073f67dd443c0073241282f5ad551c43f8"
